### PR TITLE
Link DOIs to preferred resolver

### PR DESCRIPTION
**Pull request by katrinleinweber**
Hello!

The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). This PR implements that recommendation by updating static DOI links, as well as code that generates new ones.

Code that detects or tests the old URLs should not be affected. If I did accidentally commit such a change, please let me know, and I'll fix/revert that.

Cheers :-)

### CODE REVIEW

**Comment by Michael-E-Rose** [comment]
Hi @katrinleinweber! This is a very nice and neat PR, thanks for that.  I will gladly merge it, but could you please remove the `README.ipynb` before?

**Comment by katrinleinweber** [comment]
Yes, possible, but I wonder why? It contains also only the URL updates.

**Comment by Michael-E-Rose** [comment]
Why should a jupyter notebook file be part of a python module?

**Comment by johnrkitchin** [comment]
It has been part of it nearly from the beginning. I think it shows examples in a notebook form.

**Comment by katrinleinweber** [comment]
So... Should those examples remain linked to the old resolver?

**Comment by jkitchin** [comment]
No, I think they should be updated, and reflect how to use the current code. I think your updates to the ipynb are probably appropriate. Maybe @Michael-E-Rose just forgot this file had been part of the repo all along?

**Comment by Michael-E-Rose** [comment]
Yes, indeed, I didn't know it's in that repo. Apologies for the confusion.
Do we need this file anyways?

John Kitchin <notifications@github.com> schrieb am Sa., 24. Feb. 2018,
15:29:

**Comment by jkitchin** [comment]
If it is all covered in the docs, then maybe not. It probably predates the docs.

**Comment by Michael-E-Rose** [comment]
Crazy, this is the first time I have a look at this README.ipynb.  Indeed, it predates the docs and is therefore heavily outdated (there's still instructions to create the scopus folder manually).

I go ahead and merge this PR, and in a later version I remove the README.ipynb.  Thanks again @katrinleinweber for doing this!

**Comment by katrinleinweber** [comment]
You're welcome, and thanks for merging :-)

**Pull request merged**
